version: "3.2"

services:
    geant49:
        build: .
        image: ncastello/damic-geant4.9

    damicdev:
        image: ncastello/damic-geant4.9
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix

